services:
  - type: web
    name: rapid-mixer-backend
    env: node
    plan: starter
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 5